config/routes.rb
Rails.application.routes.draw do

  root 'cocktails#index'

  get '/cocktails/:id/vote', to: 'cocktails#vote', as: :cocktail_vote

  resources :cocktails do
    resources :doses, only: [ :create ]
  end
  resources :doses, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates_uniqueness_of :cocktail, scope: :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

# , dependent: :restrict

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all.order(id: :desc)
  end

  def show
    @dose = Dose.new

  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end


  def vote
    @cocktail = Cocktail.find(params[:id])
    @cocktail.stars += 1
    @cocktail.save
    redirect_to cocktails_path(@cocktail)
  end

  def edit
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  # def index
  # end

  # def show
  # end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for [@cocktail] do |c| %>
  <%= c.input :name %>
  <%= c.input :photo %>
  <%= c.input :photo_cache, as: :hidden %>
  <%= c.submit "Update Cocktail", class: "btn btn-dark" %>
<% end %>

app/views/cocktails/edit.html.erb
<div class="page-banner">
</div>
<div class="container">

<h1><%= @cocktail.name %></h1>

<%= render 'form' %>

</div>

app/views/cocktails/index.html.erb
<div class="home-banner">
  <h1>MANY TOO MANY</h1>

  <div class="screen">
    <h3>BECAUSE 1 : N IS NEVER ENOUGH</h3>
  </div>

  <%= link_to "Add Your Drink", new_cocktail_path, class: "btn btn-primary" %>
</div>

<br>

<div class="container">
  <div class="row">

    <% @cocktails.each do |c| %>

      <div class="col-xs-12 col-sm-4">

        <div class="card"


<% if c.photo? %>

          style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                 url('<%= cl_image_path c.photo, height: 300, width: 400, crop: :fill %>')">
  <% else %>
  >
 <% end %>

                 <%= link_to(raw("<i class='fa fa-thumbs-up' aria-hidden='true'></i>"), cocktail_vote_path(c.id), class: "card-user") %>
          <%= link_to cocktail_path(c.id), class: "card-link" do %>
          <div class="card-description">
            <h2><%= c.name %></h2>
            <p>(<%= c.stars %> votes)</p>
          </div>
          <% end %>



        </div>

      </div>

    <% end %>

  </div>
</div>

<br>

<em><center><i class='fa fa-copyright' aria-hidden='true'></i>2017   Don't drink and drive.  Don't even putt. --dean martin </center></em>

<br>

app/views/cocktails/new.html.erb
<div class="page-banner">
</div>
<div class="container">

<h1>New Cocktail</h1>

<%= render 'form' %>

</div>

app/views/cocktails/show.html.erb
<div class="page-banner">
</div>

<div class="container">

<div class="container">
  <div class="row">
      <div class="col-xs-12 col-md-6">

        <br>
        <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
        <br>

      </div>
      <div class="col-xs-12 col-md-6">


<h1><%= @cocktail.name %></h1>

<%= link_to "Home", root_path %> |
<%= link_to "Edit", edit_cocktail_path(@cocktail) %> |
<%= link_to "Delete", cocktail_path(@cocktail), method: :delete, data: {confirm: "Are you sure you want to delete this cocktail?"} %> |
<%= link_to "Vote", cocktail_vote_path(@cocktail) %> |
<%= link_to "Edit Ingredients", "#", { class: 'edit-link' } %>
<br><br>

<p>Ingredients:</p>
<ul>
  <% @cocktail.doses.each do |d| %>
  <li>
    <%= d.description %> <%= d.ingredient.name %>
    <div class="form-container hidden">
      <%= link_to "Delete", dose_path(d), method: :delete %>
    </div>
  </li>
  <% end %>
</ul>

<br>

<div class="form-container hidden">
<p><strong>Add ingredients</strong></p>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, collection: Ingredient.all %>

  <!-- grouping not working !!! -->
<!--   , as: :grouped_select, group_method: :ingredient_type -->
  <%= f.submit "Add Ingredient", class: "btn btn-dark" %>
<% end %>


</div>
</div>


</div>
</div>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>N:N Cocktails</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>

 <%= favicon_link_tag(source='favicon.png') %>

  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

</head>

<body>


<%= render 'components/navbar' %>

<%= yield %>

</body>
</html>